version: "3.9"
services:
  api:
    build: ./defaultinator-api
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URI=mongodb://mongo:27017/defaultinator
    depends_on:
      - mongo
  ui:
    build: ./defaultinator-ui
    ports:
      - "3000:3000"
    environment:
      - API_BASE_URI=http://api
    depends_on:
      - api
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - defaultinator-db:/data/db:rw
volumes:
  defaultinator-db:
    driver: local
